### ISSUE TITLE
change timing of tweet

### ISSUE THREAD

**Issue by lassediercks** [lassediercks/howtotwitterbot#3]
so right now it's 8280000ms which is 2,3 hours. 

I actually wanted the bot to fire every 23 hours. 

As the content of the tweet and the initiation runs on the heroku server and the server will restart with every change, it will actually not be regular 2,3 hours but 2,3 hours after I pushed it to heroku. 

What I'd love as a solution is to tweet every 23 hours but the content can change independently

**Comment by Xiphe** [comment]
using a cronjob (ref https://github.com/lassediercks/howtotwitterbot/issues/1) will probably only work with publishing on a fixed time (daily on 23 o'clock).

So the solution will probably be invoking the script every hour but only posting every "modulus of 23"
ref https://magento.stackexchange.com/questions/73227/cron-expression-for-every-23-hours#73303
